services:
  - type: web
    name: calculation-game
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build
    startCommand: gunicorn --worker-class gthread --threads 100 -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: VITE_SAME_ORIGIN_MULTIPLAYER
        value: "true"
